/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface HcNumberSelector {
    'max': number;
    'min': number;
  }
  interface HcNumberSelectorAttributes extends StencilHTMLAttributes {
    'max'?: number;
    'min'?: number;
    'onChanged'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'HcNumberSelector': Components.HcNumberSelector;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'hc-number-selector': Components.HcNumberSelectorAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLHcNumberSelectorElement extends Components.HcNumberSelector, HTMLStencilElement {}
  var HTMLHcNumberSelectorElement: {
    prototype: HTMLHcNumberSelectorElement;
    new (): HTMLHcNumberSelectorElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'hc-number-selector': HTMLHcNumberSelectorElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'hc-number-selector': HTMLHcNumberSelectorElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
