/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HcSearch {
    'placeholder': string;
  }
  interface HcSearchAttributes extends StencilHTMLAttributes {
    'onChanged'?: (event: CustomEvent) => void;
    'placeholder'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HcSearch': Components.HcSearch;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'hc-search': Components.HcSearchAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLHcSearchElement extends Components.HcSearch, HTMLStencilElement {}
  var HTMLHcSearchElement: {
    prototype: HTMLHcSearchElement;
    new (): HTMLHcSearchElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'hc-search': HTMLHcSearchElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'hc-search': HTMLHcSearchElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
